'use client';
const productos = [
  {
    id: 1,
    nombre: 'Pantalon 1',
    precio: 60.9,
    img: '/images/pantalon-1.jpg',
    cintura: 50,
    cadera: 50,
    largo_tiro: 50,
    pierna: 50,
    marca: 'new-x',
  },
  {
    id: 2,
    nombre: 'Pantalon 2',
    precio: 76.5,
    img: '/images/pantalon-2.jpg',
    cintura: 50,
    cadera: 50,
    largo_tiro: 50,
    pierna: 50,
    marca: 'new-y',
  },
  {
    id: 3,
    nombre: 'Pantalon 3',
    precio: 99.5,
    img: '/images/pantalon-3.jpg',
    cintura: 50,
    cadera: 50,
    largo_tiro: 50,
    pierna: 50,
    marca: 'new-z',
  },
  {
    id: 4,
    nombre: 'Pantalon 4',
    precio: 88.5,
    img: '/images/pantalon-4.jpg',
    cintura: 50,
    cadera: 50,
    largo_tiro: 50,
    pierna: 50,
    marca: 'new-a',
  },
  {
    id: 5,
    nombre: 'Pantalon 5',
    precio: 95.8,
    img: '/images/pantalon-5.jpg',
    cintura: 50,
    cadera: 50,
    largo_tiro: 50,
    pierna: 50,
    marca: 'new-b',
  },
  {
    id: 6,
    nombre: 'Pantalon 6',
    precio: 59.3,
    img: '/images/pantalon-6.jpg',
    cintura: 50,
    cadera: 50,
    largo_tiro: 50,
    pierna: 50,
    marca: 'new-c',
  },
  {
    id: 7,
    nombre: 'Pantalon 7',
    precio: 68.9,
    img: '/images/pantalon-7.jpg',
    cintura: 50,
    cadera: 50,
    largo_tiro: 50,
    pierna: 50,
    marca: 'new-d',
  },
  {
    id: 8,
    nombre: 'Pantalon 8',
    precio: 95.2,
    img: '/images/pantalon-8.jpeg',
    cintura: 50,
    cadera: 50,
    largo_tiro: 50,
    pierna: 50,
    marca: 'new-e',
  },
  {
    id: 9,
    nombre: 'Pantalon 9',
    precio: 79.9,
    img: '/images/pantalon-9.jpeg',
    cintura: 50,
    cadera: 50,
    largo_tiro: 50,
    pierna: 50,
    marca: 'new-f',
  },
  {
    id: 10,
    nombre: 'Pantalon 10',
    precio: 82.7,
    img: '/images/pantalon-10.jpeg',
    cintura: 50,
    cadera: 50,
    largo_tiro: 50,
    pierna: 50,
    marca: 'new-g',
  },
  {
    id: 11,
    nombre: 'Pantalon 11',
    precio: 120,
    img: '/images/pantalon-11.jpeg',
    cintura: 50,
    cadera: 50,
    largo_tiro: 50,
    pierna: 50,
    marca: 'new-h',
  },
];

import { usePathname } from 'next/navigation';

const Producto = () => {
  const path = usePathname().split('/')[2];

  return <div>{path}</div>;
};

export default Producto;
